logging.level.root=info
logging.level.org.springframework.web=info
logging.level.org.hibernate=debug
logging.level.org.springframework.boot.security=debug

logging.level.org.springframework.security.access=debug
logging.file.path=/log
logging.file.name=myapp.log

# Local mysql database configuration.
datasource.driver-class-name=com.mysql.cj.jdbc.Driver
datasource.url= jdbc:mysql://localhost:3306/houstinglocationsdb
datasource.username= root
datasource.password=root
 
# Hibernate configuration.
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update
hibernate.dialect=org.hibernate.dialect.MySQLDialect
 
# Package to scan.
packagesToScan=com.myapplication.model


spring.mvc.dispatch-options-request=true




